### ISSUE TITLE
Task List (Module 5)

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/class-work#7]
# Assignment Description
<blockquote>
 This week we have a very important assignment as every project will develop a Task List, which enumerates the activities that need to be conducted to complete your project. Your project Task list should be consistent with the modules and subsystems identified in your completed Design Diagrams (Assignment #4). To complete the Task list you will do the following:

1) Identify and enumerate 10-25 project-specific tasks. Give one statement with an action verb per task.

2) Each task statement should identify one team member of primary responsibility. Roughly speaking, each team member should be assigned as the responsible party for about 5 significant tasks necessary to complete the project.

3) Each task statement should begin with an appropriate action verb, such as: specify, research, investigate, design, develop, obtain, document, test, validate, refine, etc.

4) Make sure that task statements use language consistent with your project description, design diagrams, and all project documentation.

5) Add your Task List as a markdown file (Tasklist.md) to your project repository.

Please see links to previous Design Reports (see Module 4) for appropriate examples of Task Lists.

Good luck, and Please contact me with any questions or concerns. 
</blockquote>

# Team assignments
Each person has to list things they want to do, then we'll add them to a file (`Tasklist.md`)
# Potential Tasks
- Develop UI for game
- Maintain project documentation
- Take meeting minutes

**Comment by IllustratedMan-code** [comment]
# David
- [ ] Research biology curriculum, lock in concepts
- [ ] Design main game-loop (with help)
- [ ] Maintain project organization (Github strategy)
- [ ] Specify Weekly Tasks

**Comment by adediu25** [comment]
# Alex

- Develop UI for game
-

**Comment by john-whiting** [comment]
# John

---

- []
- []
- []
- []
- []

**Comment by ConnorMcKinney99** [comment]
# Connor

- Enforce documentation standards
- Establish documentation standards
- Research asset library
- Prototype mini games

**Comment by IllustratedMan-code** [comment]
This is now in the schedule and milestones document.
